# Permalinks
permalink:           /:categories/:title/

# Setup
title:               Recipes
tagline:             ''
description:         ''
url:                 'http://erikwiffin.github.io/'
baseurl:             '/recipes'
paginate:            5

# About/contact
author:
  name:              Erik Wiffin
  email:             erik.wiffin@gmail.com

# Custom vars
version:             1.0.0
gems:                [jekyll-paginate]
